# Generated by Django 2.2.3 on 2019-11-13 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=tickets.models.images_folder)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('in-progress', 'In progress'), ('closed', 'Closed')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('enhancement', 'Enhancement'), ('bug', 'Bug'), ('feature', 'Feature')], max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
